// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXyyHZua6oJF4ZekgwaPYsc2aAj2kS7xA',
    appId: '1:153619363008:web:02efcb4729af175a57e925',
    messagingSenderId: '153619363008',
    projectId: 'note-sphere',
    authDomain: 'note-sphere.firebaseapp.com',
    storageBucket: 'note-sphere.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rq1rE-2DPRG-4MHvp7CemgENKhXjzlU',
    appId: '1:153619363008:android:c4e3b3cfa9b4108457e925',
    messagingSenderId: '153619363008',
    projectId: 'note-sphere',
    storageBucket: 'note-sphere.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2bG1OKAKHPYxF4fBmzascUBUi36hEFfQ',
    appId: '1:153619363008:ios:3f6260d873cc698657e925',
    messagingSenderId: '153619363008',
    projectId: 'note-sphere',
    storageBucket: 'note-sphere.appspot.com',
    iosBundleId: 'com.notesphere.noteSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2bG1OKAKHPYxF4fBmzascUBUi36hEFfQ',
    appId: '1:153619363008:ios:84b0106af5d4227a57e925',
    messagingSenderId: '153619363008',
    projectId: 'note-sphere',
    storageBucket: 'note-sphere.appspot.com',
    iosBundleId: 'com.notesphere.noteSphere.RunnerTests',
  );
}
